### ISSUE TITLE
mg-download.py retrieves no data.

### ISSUE THREAD

**Issue by phdegnan** [MG-RAST/MG-RAST-Tools#150]
I managed to get everything installed with the help of sigmavirus24 author of `requests-toolbelt` - despite having an old distribution of `requests` (older than v2.5.1 as noted in #129).

However, perhaps I messed something up, because even though mg-download.py compiles at run time without fault now:
```
$ ./tools/bin/mg-download.py -h
NAME
    mg-download

VERSION
    1

SYNOPSIS
    mg-download [ --help, --user <user>, --passwd <password>, --token <oAuth token>, --project <project id>, --metagenome <metagenome id>, --file <file id> --dir <directory name> --list <list files for given id>]
...
```

I cannot get any data from the server using the example or any other metagenome data set:
```
$ ./tools/bin/mg-download.py --metagenome mgm4441680.3 --list
+------------+-----------+---------+----------+-----------+
| Metagenome | File Name | File ID | Checksum | Byte Size |
+------------+-----------+---------+----------+-----------+
+------------+-----------+---------+----------+-----------+
```

Anything I can do to troubleshoot this?

System data:
```
$  lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04

$ pip list
apt-xapian-index (0.45)
argparse (1.2.1)
biom-format (1.3.1)
chardet (2.0.1)
cogent (1.5.3)
colorama (0.2.5)
configobj (4.7.2)
cutadapt (1.2.1)
docutils (0.11)
emperor (0.9.3)
gdata (2.0.18)
html5lib (0.999)
Jinja2 (2.7.2)
Landscape-Client (14.12)
MarkupSafe (0.18)
matplotlib (1.3.1)
mpi4py (1.3.1)
nose (1.3.1)
numpy (1.7.1)
openpyxl (1.7.0)
PAM (0.4.2)
Pillow (2.3.0)
pip (1.5.4)
prettytable (0.7.2)
pycrypto (2.6.1)
pycups (1.9.66)
pycurl (7.19.3)
Pygments (1.6)
pygobject (3.12.0)
PyNAST (1.2)
pyOpenSSL (0.13)
pyparsing (2.0.1)
pyqi (0.3.1)
pyserial (2.6)
pysmbc (1.0.14.1)
python-apt (0.9.3.5ubuntu2)
python-dateutil (1.5)
python-debian (0.1.21-nmu2ubuntu2)
pytz (2012c)
qcli (0.1.0)
reportlab (3.0)
requests (2.2.1)
requests-toolbelt (0.5.1)
roman (2.0.0)
setuptools (3.3)
six (1.5.2)
Sphinx (1.2.2)
ssh-import-id (3.21)
system-service (0.1.6)
tax2tree (1.0)
Twisted-Core (13.2.0)
urllib3 (1.7.1)
wheel (0.24.0)
wsgiref (0.1.2)
zope.interface (4.0.5)

$ pip show requests
---
Name: requests
Version: 2.2.1
Location: /usr/lib/python2.7/dist-packages
Requires: 


$ pip show requests-toolbelt
---
Name: requests-toolbelt
Version: 0.5.1
Location: /data/software/PyM/lib/python2.7/site-packages/requests_toolbelt-0.5.1-py2.7.egg
Requires: requests
```
Thanks

**Comment by phdegnan** [comment]
Hey it works today. Was the server down over the weekend then?

**Recommended code update:** *add an error message when server not available!*

**Comment by wilke** [comment]
Hi,

 we had an unexpected component failure. Thanks for your patience.

Andreas


On Dec 21, 2015, at 10:51 AM, phdegnan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey it works today. Was the server down over the weekend then?

Recommended code update: add an error message when server not available!

—
Reply to this email directly or view it on GitHub<https://github.com/MG-RAST/MG-RAST-Tools/issues/150#issuecomment-166356942>.

Andreas Wilke
Argonne National Laboratory
Mathematics and Computer Science Division
Bldg. 240 , 4F8
9700 South Cass Avenue
Argonne, IL  60439
(630) 252-3190 (phone)
(630) 252-5986.(fax)
