### ISSUE TITLE
API: annotation request fail after showing about 500 reads

### ISSUE THREAD

**Issue by dloyola** [MG-RAST/MG-RAST-Tools#151]
Hello everyone,
I'm concern about data retrival from MG-rast API, because I have tried to obtain annotation from my metagenomes using curl command or scripts availables here both fail after show some read annotation.
These are the otput message:

> Status: 500
> Access-control-allow-origin: *
> Content-Type: text/plain; charset=UTF-8
> 
> `{"ERROR":"resource request failed\nUnavailable: code=1000 [Unavailable exception] message=\"Cannot achieve consistency level LOCAL_ONE\" info={'required_replicas': 1, 'alive_replicas': 0, 'consistency': 'LOCAL_ONE'} at line 18\n\n"}`

Even to test if the problem is related to my dataset I tried using public data and the results is the same.

`curl -X GET "http://api.metagenomics.anl.gov/1/annotation/sequence/mgm4440965.3?type=function&filter=protease&source=Subsystems"``

Also tried to download data from the webpage using the API in the download section and the problem remain and even is worst beacuse does not show any entry.

I am looking forward to your reply
Thank you in advance.
Best regards

**Comment by folker** [comment]
Hi David,

please use our help desk email to communicate issues:



best,
Folker

**Comment by teharrison** [comment]
this was a backend DB timeout issue
