### ISSUE TITLE
indexerror:list index out of range

### ISSUE THREAD

**Issue by TYDSC** [MG-RAST/MG-RAST-Tools#152]
![snapshot1](https://cloud.githubusercontent.com/assets/24263042/21603394/e9852106-d1d7-11e6-99b8-65098dae4b72.png)
  how to solve this problem?

**Comment by wltrimbl** [comment]
This is due to a change in the format of data provided by the API, from sparse to a mixture of sparse and dense.  This should be fixed by PR #153 just now.

**Comment by TYDSC** [comment]
I want to use these api to download data on the site, my programming is not very good, I should modify the specific use of these APIs.
