### ISSUE TITLE
Whole project download issues

### ISSUE THREAD

**Issue by DSWallach** [MG-RAST/MG-RAST-Tools#169]
Hi, 
My lab is trying to use your download tools to pull entire projects. On line 80 of mg-download.py the string "mgm" is put in front of the value mg["metagenome_id"]. mg["metagenome_id"] already contains the "mgm" so the script makes a request for 'mgmmgm#######.#' which causes an error.

Removing the additional "mgm" allows the script to run, making requests for all the samples in the project. However no files are actually downloaded to the specified directory. Perhaps there was a change in the hosting structure?

**Comment by wltrimbl** [comment]
Thank you for noticing this issue.

When I remove the double mgm and run 

    mg-download.py --project mgp128 

It starts downloading of all of the data files for all of the metagenomes in the project.

    Making request http://api.metagenomics.anl.gov/download/mgm4447971.3?file=050.1
    Downloading mgm4447971.3.050.upload.fna for mgm4447971.3 ... Done   
    Making request http://api.metagenomics.anl.gov/download/mgm4447971.3?file=100.1
    Downloading mgm4447971.3.100.preprocess.passed.fna for mgm4447971.3 ... Done
    Making request http://api.metagenomics.anl.gov/download/mgm4447971.3?file=100.2
    Downloading mgm4447971.3.100.preprocess.removed.fna for mgm4447971.3 ... Done
    Making request http://api.metagenomics.anl.gov/download/mgm4447971.3?file=150.1

Clearly, your project is behaving differently.  Which project is it?

**Comment by DSWallach** [comment]
mgp11172
I left it running for a while and it's now downloading the samples. The first several minutes of samples are just requested without downloading.
