### ISSUE TITLE
mg-download.py

### ISSUE THREAD

**Issue by kad-ecoli** [MG-RAST/MG-RAST-Tools#181]
Starting from this week, mg-download can no longer list projects files, even for public projects:

mg-download.py --project=mgp10 --list

Making request https://api.mg-rast.org//project/mgp10?verbosity=full
Making request https://api.mg-rast.org//download/mgm4440452.7
ERROR (400): Unable to query Shock: err server returned error on SASL authentication step: Authentication failed.

I also tried adding --user and --passwd, but still have the Authentication error.

**Comment by wltrimbl** [comment]
This was a problem with authorization inside the API servers, it wasn't a problem with your user permissions.

We think we have this problem fixed now.   Please try again and let us know if API calls like this fail again.

**Comment by kad-ecoli** [comment]
It works now. Thank you.
