### ISSUE TITLE
Line 194 Index Error for mg-get-annotation-set.py 

### ISSUE THREAD

**Issue by douglasscottsdsu** [MG-RAST/MG-RAST-Tools#188]
Hello,

I am trying to run mg-annotation-set.py and I am getting an index error (IndexError: list index out of range).  I am wanting to download the functional sequence annotations for my metagenomes and organisms.  I am able to download the sequences for both function and taxons using the mg-get-sequences-for-function.py and mg-get-sequences-for-taxon.py.  These two codes do not throw an error.  

### Expected behavior
**The code with a public metagenome without error:**
mg-get-sequences-for-taxon.py --id "mgm4648965.3" --level order --source SEED > taxa_test.txt
mg-get-sequences-for-function.py --id "mgm4648965.3" --level level3 --source Subsystems > func_test.txt

### Actual behavior
_Traceback (most recent call last):
  File "/usr/local/bin/mg-get-annotation-set.py", line 4, in <module>
    __import__('pkg_resources').run_script('mglib==1.1', 'mg-get-annotation-s                                                                                et.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 654, in                                                                                 run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1441, i                                                                                n run_script
  File "/usr/local/lib/python2.7/dist-packages/mglib-1.1-py2.7.egg/EGG-INFO/s                                                                                cripts/mg-get-annotation-set.py", line 261, in <module>

  File "/usr/local/lib/python2.7/dist-packages/mglib-1.1-py2.7.egg/EGG-INFO/s                                                                                cripts/mg-get-annotation-set.py", line 194, in main

IndexError: list index out of range_

### Steps to reproduce the behavior
**The code with a public metagenome to reproduce the error:**
mg-get-annotation-set.py  --id "mgm4791794.3" --level order --source SEED > Taxa3.txt

Thank you in advance.
Doug Naliboff
Graduate Researcher
San Diego State University
Rohwer-Wegley Laboratory

**Comment by douglasscottsdsu** [comment]
Hi Will, thank you for getting back to me so quickly.  In haste, I copied the wrong code for the annotation function with an amplicon library. I received the same error and changed to a WGS library: The first two codes were listed properly in the original issue request.

## Incorrect command line with Amplicon Library (Do not use)
mg-get-annotation-set.py --id "mgm4791794.3" --level order --source SEED > Taxa3.txt

## Correct command line that throws the line index error with WGS library mgm4648965.3  (Use to get error)
mg-get-annotation-set.py --id "mgm4648965.3" --level order --source SEED > Taxa3.txt

I update MG-RAST tools yesterday morning.  Ideally, I would like to have the sequences of which Taxa is associated with each functional sequence.

Thank you for your time.

Doug Naliboff

**Comment by wltrimbl** [comment]
... after some debugging, I see that this function depends on a discontinued API call, matrix/feature.  I am not yet sure how the program seems to work for some datasets but not others.  

The functionality can be rescued, since all the data is still available from the /annotation call, but it isn't a simple parser fix.  The data has to be collected from a different API call.

**Comment by teharrison** [comment]
I can try and rescue the functionality using the newer profile resource.

**Comment by douglasscottsdsu** [comment]
Hello, I am still having errors with this command call to the API.  I get the error with the example you have listed on page 65 section 7.4 in the MG-Rast manual.  The error is listed below.

My goal is to run this command using my login, password (removed for security), and token(removed for security): 
python mg-get-annotation-set.py  --user dnaliboff --passwd  --token  --id "mgm4614042.3" --level class --source RefSeq  --output taxon_FFS.txt --evalue 8



## ERROR
dnaliboff@p:~/MG_RAST$ python mg-get-annotation-set.py --id "mgm4441680.3" --top 5 --level genus --source SEED
Making request https://api.mg-rast.org//matrix/organism?id=mgm4441680.3&group_level=genus&source=SEED&evalue=5&identity=60&length=15&result_type=abundance&hide_metadata=1
Making request https://api.mg-rast.org//status/4eaee318-4d0e-45e5-b96f-67e24dac3fdd
Making request https://api.mg-rast.org//profile/mgm4441680.3?format=mgrast&condensed=1&source=SEED
Making request https://api.mg-rast.org//profile/status/8dc555d0-dd32-45d5-8f52-f98bc36851a4
Traceback (most recent call last):
  File "mg-get-annotation-set.py", line 259, in <module>
    sys.exit( main(sys.argv) )
  File "mg-get-annotation-set.py", line 212, in main
    if (row[2] <= (opts.evalue * -1)) and (row[3] >= opts.identity) and (row[4] >= opts.length):
IndexError: string index out of range

**Comment by wltrimbl** [comment]
This tool, ``mg-get-annotation-set``, uses a now-deprecated API call, matrix/feature.  The API call matrix/feature doesn't work anymore, so the script is failing when it finds no data in the response.  We need to update the documentation to remove/replace this script.

This functionality to return sequences with annotations has been moved to the "annotation" API call, for which we don't seem to have a driver script at the moment.  ``mg-extract-sequences`` does something similar, but is intended to collect similarly-annotated sequences from multiple datasets.  

I think this command

    curl 'http://mg-rast.org/annotation/sequence/mgm4441680.3?id=mgm4441680.3&evalue=5&identity=60&filter_level=genus&format=fasta&no_cutoffs=0&source=SEED&type=organism'

does what you were intending.

**Comment by folker** [comment]
lets make sure to change the documentation as well...

**Comment by douglasscottsdsu** [comment]
@wltrimbl  I cannot get the curl to work with my login, password, and token.  Can you give me an example?
@teharrison  I have tried to pull the sequences by class (Flavobacteriia), however, nothing is downloaded (code below).  I would like to pull all the sequences that hit to a class by class name.  Is there a way to do this?

python mg-get-sequences-for-taxon.py --id mgm4441680.3 --source SEED --name Flavobacteriia --level class --evalue 5 --identity 60 > flav.txt  


Thank you for all your help.  I use to be able to pull all this information from the web browser several years ago.  I would like to avoid reannotating my data for my thesis.

**Comment by wltrimbl** [comment]
You misspelled Flavobacteria.

**Comment by wltrimbl** [comment]
The authorization header for the API is a header "Authorization" with the content 

    Authorization: mgrast $MGRKEY  

For instance 

    curl -H "Authorization: mgrast $MGRKEY"   

where $MGRKEY has the value of your user's web API key.
