### ISSUE TITLE
get_auth_token() is returning empty value

### ISSUE THREAD

**Issue by felipeborim789** [MG-RAST/MG-RAST-Tools#194]
### Expected behavior
get_auth_token()
"VALUE"

### Actual behavior
get_auth_token()
''

### Steps to reproduce the behavior
from mglib import get_auth_token, obj_from_url, API_URL
get_auth_token()

### Note
I have already tried:
- Updating the repository locally MG-RAST-Tools/
- Reinstalling MG-RAST-Tools: python setup.py build
- Updating mglib: pip install mglib --upgrade

**Comment by teharrison** [comment]
I'm not sure what your problem is.  get_auth_token() is a helper function in the shared library that our scripts use, it expects the token to either be in a shell environmental variable or passed to the script via a command line option.  Which script is it not working in?

**Comment by wltrimbl** [comment]
To restate the above.. get_auth_token retrieves the token from the MGRKEY environment variable.  

You must get the authorization token from the upload page and put its value into MGRKEY.
