### ISSUE TITLE
download json file(s) and upload it to Analysis for visualization

### ISSUE THREAD

**Issue by Jigyasa3** [MG-RAST/MG-RAST-Tools#202]
I have used the mg-download.py script which gives the metadata, not the complete data . I am looking for a way to download the data (eg- my metagenome against KEGG database), and uploading it back to MG-RAST for comparative analysis between ~200 samples.

I can do it manually from the Analysis page, but don't want to manually download data for ~200 samples for comparison.

Is there any other way?

**Comment by wltrimbl** [comment]
The analysis page does not support data from outside sources, but you can get the data out of the API.

Essentially all of the anaysis page functionality is built on top of the 
http://api.mg-rast.org/matrix API query

Try the abundance-matrix.py script:

abundance_matrix.py -m mgm4447101.3,mgm4447102.3,mgm4447103.3 -g genus -k $MGRKEY

abundance_matrix.py -m mgm4447101.3,mgm4447102.3,mgm4447103.3 -s KEGG -k $MGRKEY

These calls are time-consuming, but you don't have to tend to them while you are waiting for the API to get your data ready.
