### ISSUE TITLE
Error-Making request https://api.mg-rast.org//status/

### ISSUE THREAD

**Issue by Jigyasa3** [MG-RAST/MG-RAST-Tools#203]
I am running the following script-
_$/home/MG-RAST-Tools/scripts/mg-abundant-functions.py --level level3 --source Subsystems --id "mgmxxxx.x" --token "my_webkey"_

But it doesn't go past
_Making request https://api.mg-rast.org//status/_

Question-
1. why is not able to connect to API?
2. Is there a way to specify an output file in the script? OR its a standard output?

**Comment by wltrimbl** [comment]
The following public dataset does not produce this error.  

mg-abundant-functions.py --level level3 --source Subsystems --id "mgm4514486.3"

Can you give me the id of a dataset that has this problem?

**Comment by wltrimbl** [comment]
Closing for lack of follow-up
