### ISSUE TITLE
KeyError in md-download.py

### ISSUE THREAD

**Issue by capoony** [MG-RAST/MG-RAST-Tools#208]
Hi all, 

first of all, thanks a lot for this great tool!!

When running the mg-download.py script, I got the following error message:

 _File "\~/Documents/GitHub/MG-RAST-Tools/scripts/mg-download.py", line 125, in <module>
    sys.exit(main(sys.argv))
  File "\~/Documents/GitHub/MG-RAST-Tools/scripts/mg-download.py", line 115, in main
    file_download(token, f, dirpath=mgdir)
  File "\~/Documents/GitHub/MG-RAST-Tools/scripts/mg-download.py", line 43, in file_download
    file_from_url(info['url'], fhandle, auth=auth)
KeyError: 'url'_

It apears as if the dictionary "f" does not contain an "url" key. 

I coded a simple, yet not very elegant, work-around (see edits in the function "file_download") which work and which may be useful.

Cheers, Martin 

[mg-download.py.zip](https://github.com/MG-RAST/MG-RAST-Tools/files/4362689/mg-download.py.zip)

**Comment by wltrimbl** [comment]
Thank you for your bug report.

Can you help us out by further specifying a particular invokation that produces this error?  It does not produce this error with every dataset or with every set of parameters, and if you can guide the developers to reproduce the error themselves, it will get fixed faster.
