### ISSUE TITLE
installing MG-RAST-Tools [Ubuntu 20.04 LTS]

### ISSUE THREAD

**Issue by nataliagaeta29** [MG-RAST/MG-RAST-Tools#211]
Hello

I am trying to install MG-RAST-Tools on my Ubuntu 20.04 LTS.
When add the follow command:   sudo python setup.py install, I get the following error message:

Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
ImportError: No module named setuptools

I've uninstalled and installed setuptools with no success.
I am using Python 3.7.6

Any clue on how to solve this issue?

Thank you

**Comment by wltrimbl** [comment]
You need python3-setuptools to build MG-RAST-Tools, and you can get it on ubuntu 20.04 with

    apt-get update && apt-get install -y python3-setuptools
