### ISSUE TITLE
ImportError when using "mg-inbox.py"

### ISSUE THREAD

**Issue by SebH87** [MG-RAST/MG-RAST-Tools#215]
Hi,

I would like to use the "mg-inbox.py" script. When running the script ($ python mg-inbox.py --help), I receive the following error:

Traceback (most recent call last):
  File "mg-inbox.py", line 9, in <module>
    from mglib import VERSION, API_URL, AUTH_LIST, get_auth_token, obj_from_url, SHOCK_URL, post_file, get_auth, login
ImportError: cannot import name 'VERSION'

I am using the newest release of mglib and I've already tested different python versions (2.7, 3.6, 3.9), but the error persists. Any ideas what's going on here?

Thank you very much in advance!

Sebastian

**Comment by wilke** [comment]
Dear Sebastian,

Unfortunately I can not reproduce the error. I tried:

```
docker pull ubuntu
docker run -ti --rm ubuntu:latest bash
apt update
apt upgrade
apt install python3 python3-pip git
git clone https://github.com/MG-RAST/MG-RAST-Tools.git
cd MG-RAST-Tools/
python3 setup.py build
python3 setup.py install
mg-inbox.py --help
```

Do you have more than one version in your path? How did you install the scripts?

Andreas

**Comment by SebH87** [comment]
Dear Andreas,

Thank you for your answer, this solved the issue now!

Best,

Sebastian
